In [1]:
import cv2
import numpy as np

In [ ]:
while True:
    
    # Reading The Image
    img=cv2.imread('Colored Coin Image.png',1)
    
    #Converting The Image To HSV Format
    hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    
    #Displaying The HSV Converted Image
    cv2.imshow('HSV Image',hsv)
    
    #Displaying The Original Image
    cv2.imshow('Original Image',img)
    
    #In Order To Do Threshold For (Blue Color) Of HSV Image
    Min_range=np.array([110,50,50]) # Lower Range Value Of Blue Colored Image
    Max_range=np.array([130,255,255])# Higher Range value Of Blue Colored Image
    
    #Printing The Min and Max Range Of Blue Color
    print('The Maximum And Minimum Range value Of Blue Color')
    print(Min_range)
    print(Max_range)
    
    #Thresholding The HSV Image
    mask=cv2.inRange(hsv,Min_range,Max_range)
    
    #Displaying The Threshold Image
    cv2.imshow('Threshold Image',mask)
    
    #Printing The Threshold Array
    print('\nPrinting The mask Value')
    print(mask)
    
    #Extracting The Blue Color From The Image
    Extracted_img=cv2.bitwise_and(img,img,mask=mask)
    
    #Printing The Extracted Image Array
    print('\nPrinting The Extracted Image Value')
    print(Extracted_img)
    
    #Displaying The Extracted Image
    cv2.imshow('Extracted Image',Extracted_img)
    
    if cv2.waitKey(0):
        break
        
cv2.destroyAllWindows()

The Maximum And Minimum Range value Of Blue Color
[110  50  50]
[130 255 255]

Printing The mask Value
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Printing The Extracted Image Value
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
